language: ruby
script:
  - bundle exec rake db:structure:load ON_ERROR_STOP=0
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - psql -c 'create database dgidb_test;' -U postgres
rvm:
  - "2.3.3"
env:
  - RAILS_ENV=test TRAVIS_BUILD=true
notifications:
  email: false
git:
    submodules: false
