sources:
  title_main: About DGIdb's source data
  title_small: drug gene interaction database
  description: DGIdb aggregates drug, gene, and interaction information from a variety of sources. They are listed below.
